@echo off
set savedir=Z:\media\SHARE\roms\Proton\Diablo.pc\Saves
cls
del %savedir%\levels\towndata\town.pal
del %savedir%\levels\l1data\l1_1.pal
del %savedir%\levels\l1data\l1_2.pal
del %savedir%\levels\l1data\l1_3.pal
del %savedir%\levels\l1data\l1_4.pal
del %savedir%\levels\l1data\l1_5.pal
del %savedir%\levels\l2data\l2_1.pal
del %savedir%\levels\l2data\l2_2.pal
del %savedir%\levels\l2data\l2_3.pal
del %savedir%\levels\l2data\l2_4.pal
del %savedir%\levels\l2data\l2_5.pal
del %savedir%\levels\l3data\l3_1.pal
del %savedir%\levels\l3data\l3_2.pal
del %savedir%\levels\l3data\l3_3.pal
del %savedir%\levels\l3data\l3_4.pal
del %savedir%\levels\l3data\l3_5.pal
del %savedir%\levels\l4data\l4_1.pal
del %savedir%\levels\l4data\l4_2.pal
del %savedir%\levels\l4data\l4_3.pal
del %savedir%\levels\l4data\l4_4.pal
del %savedir%\levels\l4data\l4_5.pal
del %savedir%\NLevels\l5data\L5Base.PAL
del %savedir%\NLevels\l6data\l6base1.pal
del %savedir%\NLevels\l6data\l6base2.pal
del %savedir%\NLevels\l6data\l6base3.pal
del %savedir%\NLevels\l6data\l6base4.pal
del %savedir%\NLevels\l6data\l6base5.pal